### ISSUE TITLE
[Feature Request]: Add form validation

### ISSUE THREAD

**Issue by seecs-test2** [DawoodMehmood/Jobify#1]
Currently, the following input field accepts any random input string. Validation needs to be added to confirm whether the string is a valid Url

![image](https://github.com/DawoodMehmood/Jobify/assets/113658407/d50a9dd7-9673-48bb-9536-85f347378712)

**Comment by DawoodMehmood** [comment]
Thanks for pointing it out.
This problem can be solved by updating the `workoutModel.js` file present at `jobify/backend/models/workoutModel.js`.
You need to add these lines of code in the `applyLink` element of `workoutModel.js` which will validate whether a string passed is a valid URL or not using Regex and output an error message if it is not a valid URL.


```
applyLink: {
    type: String,
    required: true,
    validate: {
      validator: function (value) {
        // Regular expression to validate URL
        const urlRegex = /^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([/\w.-]*)*\/?$/;
        return urlRegex.test(value);
      },
      message: 'Invalid URL format',
    },
  },
```
